import test from "node:test";
import assert from "node:assert/strict";
import { onRequestGet as getPublic } from "../functions/api/orders/[token].js";
import { onRequestGet as getAdmin } from "../functions/api/admin/orders/index.js";
import { fakeDb, responseJson } from "./helpers/fake-db.mjs";
const token="123e4567-e89b-12d3-a456-426614174000",pedido={id:7,token_publico:token,produto_nome:"Pedido com 2 itens",quantidade:3,valor_total_centavos:3500,status_pagamento:"PAGO",mp_order_id:null,mp_status:"processed",mp_status_detail:"accredited",pago_em:"2026-08-23 01:00:00"},itens=[{pedido_id:7,produto_id:1,produto:"Brigadeiro",produto_nome:"Brigadeiro",quantidade:2,valor_unitario_centavos:1000,valor_total_centavos:2000},{pedido_id:7,produto_id:2,produto:"Pudim",produto_nome:"Pudim",quantidade:1,valor_unitario_centavos:1500,valor_total_centavos:1500}];
test("API pública retorna todos os itens",async()=>{const x=fakeDb(sql=>sql.includes("FROM pedidos WHERE token_publico")?{first:()=>pedido}:sql.includes("FROM pedido_itens")?{all:()=>({results:itens.map(({pedido_id,produto_nome,...i})=>i)})}:{});const r=await getPublic({params:{token},env:{DB:x}}),b=await responseJson(r);assert.equal(r.status,200);assert.equal(b.pedido.itens.length,2);assert.equal(b.pedido.quantidade_total,3)});
test("API pública rejeita token inválido",async()=>assert.equal((await getPublic({params:{token:"invalido"},env:{}})).status,400));
test("API administrativa agrega itens e preserva snapshot legado",async()=>{const legado={...pedido,id:6,produto_nome:"Produto antigo",quantidade:1},x=fakeDb(sql=>{if(sql.includes("FROM admin_sessoes"))return{first:()=>({id:1,nome:"Admin",ativo:1,papel:"ADMIN"})};if(sql.includes("FROM pedido_itens"))return{all:()=>({results:itens})};if(sql.includes("FROM pedidos ORDER BY"))return{all:()=>({results:[pedido,legado]})};if(sql.includes("status_pagamento = 'PENDENTE'"))return{all:()=>({results:[]})};return{}});const r=await getAdmin({request:new Request("https://loja.test/api/admin/orders",{headers:{Cookie:"rp_admin_session=sessao"}}),env:{DB:x}}),b=await responseJson(r);assert.equal(r.status,200);assert.equal(b.pedidos[0].itens.length,2);assert.deepEqual(b.pedidos[1].itens,[]);assert.equal(b.pedidos[1].produto_nome,"Produto antigo")});
