import test from "node:test";
import assert from "node:assert/strict";
import { baixarEstoquePedido } from "../functions/lib/stock.js";
import { fakeDb } from "./helpers/fake-db.mjs";
function db({pedido,itens=[],insuficiente=null,batchChanges=1}){return fakeDb(sql=>{if(sql.includes("FROM pedidos WHERE id"))return{first:()=>pedido};if(sql.includes("FROM pedido_itens")&&sql.includes("ORDER BY id"))return{all:()=>({results:itens})};if(sql.includes("HAVING i.produto_id"))return{first:()=>insuficiente};return{}},async ss=>ss.map((_,i)=>({success:true,meta:{changes:i===ss.length-1?batchChanges:1}})))}
test("não baixa pedido inexistente, não pago ou já processado",async()=>{for(const pedido of[null,{id:1,status_pagamento:"PENDENTE"},{id:1,status_pagamento:"PAGO",estoque_baixado_em:"agora"}]){const x=db({pedido});assert.deepEqual(await baixarEstoquePedido({DB:x},1),{ok:true,baixado:false});assert.equal(x.batches.length,0)}});
test("recusa tudo quando qualquer item está sem estoque",async()=>{const x=db({pedido:{id:1,status_pagamento:"PAGO",estoque_baixado_em:null},itens:[{id:10,produto_id:1,quantidade:2}],insuficiente:{id:10,produto_id:1,estoque:1,quantidade:2}});assert.deepEqual(await baixarEstoquePedido({DB:x},1),{ok:false,baixado:false,erro:"ESTOQUE_INSUFICIENTE",item_id:10});assert.equal(x.batches.length,0)});
test("baixa todos os itens no mesmo batch",async()=>{const itens=[{id:10,produto_id:1,quantidade:2},{id:11,produto_id:2,quantidade:1}],x=db({pedido:{id:1,status_pagamento:"PAGO",estoque_baixado_em:null},itens});assert.deepEqual(await baixarEstoquePedido({DB:x},1),{ok:true,baixado:true});assert.equal(x.batches[0].length,1+itens.length*2+1)});
test("concorrente já concluído não conta como nova baixa",async()=>{const x=db({pedido:{id:1,status_pagamento:"PAGO",estoque_baixado_em:null},itens:[{id:10,produto_id:1,quantidade:1}],batchChanges:0});assert.deepEqual(await baixarEstoquePedido({DB:x},1),{ok:true,baixado:false})});
test("pedido pago sem itens não altera estoque",async()=>{const x=db({pedido:{id:1,status_pagamento:"PAGO",estoque_baixado_em:null},itens:[]});assert.deepEqual(await baixarEstoquePedido({DB:x},1),{ok:false,baixado:false,erro:"ITENS_NAO_ENCONTRADOS"})});
